### PR TITLE
chore: use colors from @dhis2/ui-core

### PR DESCRIPTION
**Pull request by janhenrikoverland**
~Depends on https://github.com/dhis2/analytics/pull/33!~

Use shared colors.

### CODE REVIEW

**Comment by edoardo** [comment]
@cooper-joe provided the following color codes mapping between the colors file and ui-core theme
colors:

>const accentPrimaryDark = '#004BA0' -> primary800
const accentPrimary = '#1976D2' -> primary600
const accentPrimaryLight = '#63A4FF' -> primary300
const accentPrimaryLightest = '#EAF4FF' -> primary050

>const accentSecondaryDark = '#004C40' -> secondary800
const accentSecondary = '#00796B' -> secondary600
const accentSecondaryLight = '#48A999' -> secondary300
const accentSecondaryLightest = '#B2DFDB' -> secondary200
const accentSecondaryTransparent = '#D9ECEB' -> secondary100

>const black = '#000000' -> grey900
const greyDark = '#494949' -> grey700
const grey = '#9E9E9E' -> grey500
const greyLight = '#E0E0E0' -> grey300
const blueGrey = '#ECEFF1' -> grey200
const lightBlue = '#BBDEFB' -> blue200
const snow = '#F4F6F8' -> grey050
const white = '#FFFFFF' -> white

>const negative = '#E53935' -> red500
const warning = '#F19C02' -> yellow500
const positive = '#3D9305' -> green500
const info = '#EAF4FF' -> grey300

>// TODO remove these?
const paleGrey = '#FAFAFA' -> grey100
const lightGrey = '#F5F5F5' -> grey100
const charcoalGrey = '#CCCCCC' -> grey400
const blue = '#004BA0' -> blue800

**Comment by edoardo** [comment]
ui-core seems to cause a problem in the app build.

```
Failed to minify the code from this file: 
 	/home/travis/build/dhis2/data-visualizer-app/node_modules/@dhis2/ui-core/build/es/Button/index.js:9
```
See: https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify

**Comment by edoardo** [comment]
Found one more place with hardcoded colors: App.css.

**Comment by jenniferarnesen** [comment]
@edoardo Approved. When you squash merge, could you include Viktor's explanation of the webpack changes in the commit description?

**Pull request merged**
